Improve cpuonly install (#212)
* conda.yml: cpuonly on its own line

Conda requires `cpuonly` as a separate dependency, separated by a space
(conda command) or on separate lines (conda.yml). From PyTorch docs:

conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1
cpuonly -c pytorch
(https://pytorch.org/get-started/previous-versions/#linux-and-windows-4)

This is unlike pip, which uses a plus (+) to indicate cpu builds; for
pytorch (torch>=1.0,<=1.12.1+cpu).

Prior to this change, `cpuonly` is not recognized by conda, and instead GPU
versions are installed by default (tested on 4 different CPU-only
environments). This causes errors when attempting to run sample
gt4sd code.

* require transformers <=4.24.0 instead of <4.26.0

This avoids an error occurring in gt4sd-core/notebooks/diffusion-demo.ipynb
(https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/diffusion-demo.ipynb)

The error occurs in the cell with this code:

prompt = "Generative models on mars!"

Here is the error (e.g., when transformers 4.25.1 is installed):

ValueError: The component <class
'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of
<class
'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>
cannot be loaded as it
does not seem to have any of the loading methods defined in
{'ModelMixin': ['save_pretrained', 'from_pretrained'],
'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline':
['save_pretrained', 'from_pretrained'],
'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'],
'PreTrainedTokenizer': ['save_pretrained',
'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained',
'from_pretrained'], 'PreTrainedModel':
['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin':
['save_pretrained', 'from_pretrained']}.

With transformers 4.24.0 installed, this error is avoided and
the entire notebook runs without error.