require transformers <=4.24.0 instead of <4.26.0
This avoids an error occurring in gt4sd-core/notebooks/diffusion-demo.ipynb
(https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/diffusion-demo.ipynb)

The error occurs in the cell with this code:

prompt = "Generative models on mars!"

Here is the error (e.g., when transformers 4.25.1 is installed):

ValueError: The component <class
'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of
<class
'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>
cannot be loaded as it
does not seem to have any of the loading methods defined in
{'ModelMixin': ['save_pretrained', 'from_pretrained'],
'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline':
['save_pretrained', 'from_pretrained'],
'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'],
'PreTrainedTokenizer': ['save_pretrained',
'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained',
'from_pretrained'], 'PreTrainedModel':
['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin':
['save_pretrained', 'from_pretrained']}.

With transformers 4.24.0 installed, this error is avoided and
the entire notebook runs without error.